name: "Cron announcements"

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r _telegram/requirements.txt

      - name: execute py script # run main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
        run: python _telegram/announcements.py
